# -*- coding: utf-8 -*-
"""mnist_classification_dense_tensorflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUDrUjv-rcjpGES-k47QJyE3dfa8RAik
"""

import tensorflow as tf
import cv2
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist #veri setini cagirdik
from tensorflow.keras.models import Sequential#ANN modeli icin
from tensorflow.keras.layers import Dense, Dropout#ANN katmanlari icin
from tensorflow.keras.optimizers import Adam #optimizer

(x_train,y_train),(x_test,y_test)=mnist.load_data()
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

img=x_train[0]
stages = {"orijinal":img}
eq=cv2.equalizeHist(img)
stages["Histogram Esitleme"]=eq
#gaussian blur:gürültü azaltma
blur=cv2.GaussianBlur(eq,(5,5),0)
stages["gaussian blur:"]=blur
#canny ile kenar tespiti
edges =cv2.Canny(blur,50,150)
stages["canny kenarlari"]=edges

#görsellestirme
fig,axes=plt.subplots(2,2,figsize=(6,6))
axes=axes.flat
for ax,(title,im) in zip(axes,stages.items()):
  ax.imshow(im,cmap="gray")
  ax.set_title(title)
plt.tight_layout()
plt.show()

def preprocess_image(img):
  img_eq=cv2.equalizeHist(img)#hist esitleme
  img_blur=cv2.GaussianBlur(img_eq,(5,5),0)#gaussian blur
  img_edges=cv2.Canny(img_blur,50,150)#canny kenar tespiti
  features=img_edges.flatten()/255.0#normalizasyon
  return features

num_train=60000
num_test=10000
x_train_pre=np.array([preprocess_image(img) for img in x_train[:num_train]])
y_train_pre=y_train[:num_train]
x_test_pre=np.array([preprocess_image(img) for img in x_test[:num_test]])
y_test_pre=y_test[:num_test]

#model tanımı
model=Sequential()
model.add(Dense(128,activation="relu",input_shape=(784,)))
model.add(Dropout(0.5))
model.add(Dense(64,activation="relu"))
model.add(Dense(10,activation="softmax"))

#compile model
model.compile(optimizer="adam",loss="sparse_categorical_crossentropy",metrics=["accuracy"])

print(model.summary())

history2=model.fit(x_train_pre,y_train_pre,
batch_size=32,
epochs=20,
validation_data=(x_test_pre,y_test_pre),
verbose=2)

test_loss,test_acc=model.evaluate(x_test_pre,y_test_pre)
print(f"Test Loss:{test_loss:.4f},Test Accuracy:{test_acc:.4f}")

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(history2.history["loss"],label="train loss")
plt.plot(history2.history["val_loss"],label="val loss")
plt.legend()
plt.subplot(1,2,2)
plt.plot(history2.history["accuracy"],label="train accuracy")
plt.plot(history2.history["val_accuracy"],label="val accuracy")
plt.legend()
plt.show()